### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by stijnb1234** [ImranDoet/SpiderCore#3]
Hello,

I'm interesed in your Quidditch plugin, and therefor I need this core plugin. But the main class doesn't even implements JavaPlugin. How do I need to use this core plugin?

Thanks in advance.

Kind regards,

Stijn

**Comment by stijnb1234** [comment]
Or a better question, how to import spidercore in maven?

**Comment by stijnb1234** [comment]
Fixed by using jitpack.

**Comment by ImranDoet** [comment]
Do you still need help?
